apiVersion: v1
kind: Secret
metadata:
  name: jenkins-service-account-token
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
