apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
  namespace: {{ .Values.namespace | quote }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: Opaque
data:
  TELEGRAM_TOKEN: {{ .Values.telegramToken | b64enc | quote }}   # This will base64-encode the token


#apiVersion: v1
#kind: Secret
#metadata:
#  name: telegram-token
#  namespace: {{ .Values.namespace }}
#type: Opaque
#data:
#  TELEGRAM_TOKEN: {{ .Values.telegramToken | quote }}