apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eldiabloj/polyboy-kubernetes--tampelts.git'
    targetRevision: HEAD
    path: 'kubernetes/nginx-app/templates'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
