apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-roles
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins-pod-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "deployments", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
