replicas: 1
image:
  repository: eldiabloj/polybot
  tag: 180
env: production
resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m
namespace:
hpa:
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 50
telegramToken: "6648578545:AAFNnFkbsJZOZiRu6TenQ7ufwJedsB_OaEo"




