apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: eldiabloj/python-app:latest
        ports:
        - containerPort: 90
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: app-volume
        hostPath:
          path: /home/oj/PycharmProjects/ImageProcessingService/app
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  ports:
  - port: 90
    targetPort: 90
  selector:
    app: python-app



#kubectl create secret docker-registry my-registry-key
#  --docker-username=eldiabloj
#  --docker-password=dckr_pat_xG2j-SkuYvZBl5aNtijP6e2jCAs
#  --docker-email=oshrbg@gmail.com
       # volumeMounts:
        #- name: app-volume
         # mountPath: /app
